//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMBUY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEAMBUY()
        {
            this.TEAMORDER = new HashSet<TEAMORDER>();
        }
    
        public string TEAMID { get; set; }
        public string MEMBERID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public decimal LEASTAMOUNT { get; set; }
        public string STATUS { get; set; }
    
        public virtual MEMBERS MEMBERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAMORDER> TEAMORDER { get; set; }
    }
}
